categories:
  - name: "Food & Drinks"
    subcategories:
      - "Groceries"
      - "Restaurants"
      - "Coffee & Cafes"
      - "Other"

  - name: "Shopping"
    subcategories:
      - "Clothing"
      - "Electronics"
      - "Home Goods"
      - "Personal Care"
      - "Sport"
      - "Other hobbies"
      - "Tools"
      - "Other"

  - name: "Housing"
    subcategories:
      - "Rent"
      - "Internet"
      - "Electricity"
      - "Heating"
      - "Water"
      - "Other"

  - name: "Transportation"
    subcategories:
      - "Public Transport"
      - "Taxi & Rideshare"
      - "Bicycle"
      - "Other"

  - name: "Car"
    subcategories:
      - "Fuel"
      - "Maintenance"
      - "Insurance"
      - "Parking"
      - "Other"

  - name: "Life & Entertainment"
    subcategories:
      - "Streaming Services"
      - "Events & Activities"
      - "Hobbies"
      - "Holiday, Trips, Hotels"
      - "Flights"
      - "Active Sport"
      - "Culture & Sport Events"
      - "Other"

  - name: "Healthcare"
    subcategories:
      - "Medicine"
      - "Doctor & Dentist"
      - "Health Insurance"
      - "Other"

  - name: "Communication & PC"
    subcategories:
      - "Mobile"
      - "Software, Apps, Games"
      - "Other"

  - name: "Financial expenses"
    subcategories:
      - "Bank Fees"
      - "Insurance"
      - "Loans & Credits"
      - "Other"

  - name: "Investments"
    subcategories:
      - "Investments"

  - name: "Income"
    subcategories:
      - "Salary"
      - "Investment Return"
      - "Sales"
      - "Other"

  - name: "Other"
    subcategories:
        - "Uncategorized"
